server:
  port: 8080
  servlet:
    contextPath: /${spring.application.name}/v1
spring:
  application:
    name: mssivimss-facturacion
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  main:
    allow-circular-references: true

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

endpoints:
  mod-catalogos: ${msit_CATALOGOS}
  ms-reportes: ${msit_REPORTES_GENERALES}
  consulta-rfc: ${msit_CONSULTA_RFC}
  envio-correo-factura: ${msit_CORREO_FACTURA}

jwt:
  secretkey-flujo: ${msit_SECRET_KEY}
  secretkey-dominios: ${msit_SECRET_KEY_DOMINIO}
  expiration-milliseconds: ${msit_SECRET_KEY_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

resilience4j.circuitbreaker:
  circuitBreakerAspectOrder: 1
  instances:
    msflujo:
      automaticTransitionFromOpenToHalfOpenEnabled: 'true'
      failureRateThreshold: ${msit_HILOS}
      slidingWindowType: COUNT_BASED
      event-consumer-buffer-size: '10'
      registerHealthIndicator: 'true'
      waitDurationInOpenState: ${msit_TIEMPO_DURACION}
      permittedNumberOfCallsInHalfOpenState: ${msit_NUMERO_INTENTOS}
      slidingWindowSize: '5'
resilience4j.retry:
  retryAspectOrder: 2
  instances:
    msflujo:
      maxAttempts: ${msit_NUMERO_INTENTOS}
      waitDuration: ${msit_TIEMPO_DURACION}
resilience4j.timelimiter:
  timeLimiterAspectOrder: 3
  instances:
    msflujo:
      timeout-duration: ${msit_TIEMPO_DURACION}

formato_fecha: ${msit_FORMATO_FECHA}
ruta-log: ${msit_RUTA_LOG}

jonima_user: ${msit_JONIMA_USER}
jonima_pass: ${msit_JONIMA_PASS}
jonima_appName: ${msit_JONIMA_APPNAME}
jonima_owner: ${msit_JONIMA_OWNER}
jonima_procedure_crear: ${msit_JONIMA_PROCEDURE_CREAR}
jonima_procedure_cancelar: ${msit_JONIMA_PROCEDURE_CANCELAR}
rfc_fibeso: ${msit_RFC_FIBESO}