
package com.imss.sivimss.facturacion.service.rfc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SATPatrones", targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SATPatrones {


    /**
     * 
     * @param datosEntrada
     * @return
     *     returns com.imss.sivimss.facturacion.SalidaSAT
     */
    @WebMethod
    @WebResult(targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws")
    @RequestWrapper(localName = "getPatron", targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws", className = "com.imss.sivimss.facturacion.GetPatron")
    @ResponseWrapper(localName = "getPatronResponse", targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws", className = "com.imss.sivimss.facturacion.GetPatronResponse")
    public SalidaSAT getPatron(
        @WebParam(name = "datosEntrada", targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws")
        EntradaSAT datosEntrada);

}
